39 feat criar uma página sobre nós
ceos-jr/ceos-institucional pull request #58
Opened 2023-03-07 00:05 UTC by en20

# Description

Closes # (linke sua issue aqui)

## Tipo de mudança

- [ ] Bug fix (mudança não críticaque conserta uma issue)
- [ ] New feature (mudança não crítica que adiciona uma nova feature)
- [ ] Mudança crítica (Concerto ou uma feature que pode quebrar funcionalidades antigas)
- [ ] Apenas mudança de documentação

# Checklist:

- [ ] Realizei uma revisão do meu código
- [ ] Eu comentei meus códigos, particularmente nas aŕeas mais difíceis
- [ ] Eu fiz as mudanças correspondentes na documentação
- [ ] Minhas mudanças não geraram nenhum warning
- [ ] Qualquer mudança pendente na main branch já foi implementada nessa branch

2023-03-07 19:55 UTC, talDoFlemis commented on package.json
> +    "@chakra-ui/react": "^2.5.1",
remover todas essa dependencias que foram instaladas justamente com as modificacoes que alteraram o package-lock.json

2023-03-07 19:59 UTC, talDoFlemis commented on src/components/Navbar.tsx
> +type NavItemData = {
precisa de uma interface e um tipo pra mesma estrutura de dados esperada?

2023-03-07 20:04 UTC, talDoFlemis requested changes
Olha aqui vcs dois @en20 @Lu1z-Gust4v0

2023-03-07 20:04 UTC, talDoFlemis commented on src/pages/about-us.tsx
> +              src="/images/imagemtime.jpg"
tem 3 imagems com o mesmo conteúdo, escolher só uma e deletar as outras

2023-03-07 20:04 UTC, talDoFlemis commented on src/pages/about-us.tsx
> +              src="/images/imagemtime.jpg"
além disso elas estão em qualidade de 1200p se for possível pegar algo com resolução maior, pergunte ao marcelo se ele tem

2023-03-07 20:04 UTC, talDoFlemis commented on src/components/Services/Services.tsx
> -import { PossibleServices } from "../typings/services"
deletar esse arquivo services já que não vai usar mais

2023-03-07 20:04 UTC, talDoFlemis commented on src/pages/about-us.tsx
> +      <Head>
adicionar meta de description aqui

2023-03-07 20:04 UTC, talDoFlemis commented on src/pages/about-us.tsx
> +        <title>About us • CEOS</title>
E trocar esse nome em inglês pra portugues tio

2023-03-07 22:59 UTC, Lu1z-Gust4v0 commented on package.json
> +    "@chakra-ui/react": "^2.5.1",
quais precisam remover?

2023-03-07 23:00 UTC, Lu1z-Gust4v0 commented on src/components/Navbar.tsx
> +type NavItemData = {
Eu só coloquei pra deixar os tipos mais claros

2023-03-07 23:55 UTC, talDoFlemis commented on package.json
> +    "@chakra-ui/react": "^2.5.1",
todos que foram adicionados nesse PR

2023-03-08 16:06 UTC, talDoFlemis requested changes
@en20 @Lu1z-Gust4v0

2023-03-08 16:06 UTC, talDoFlemis commented on src/pages/sobre-nos.tsx
> +              src="/images/team.jpg"
falta otimizar essa imagem que ta baixando 4000 px sempre

2023-03-08 16:09 UTC, talDoFlemis commented on src/pages/sobre-nos.tsx
> +              src="/images/team.jpg"
![image](https://user-images.githubusercontent.com/33133120/223766581-4b96d2a1-8f57-4ae6-addc-764f0a3f0097.png)

2023-03-08 20:20 UTC, talDoFlemis requested changes
olha aqui @Lu1z-Gust4v0

2023-03-08 20:20 UTC, talDoFlemis commented on src/pages/index.tsx
> +    text: "Início",
esse início não ta levando para o hero ta travado na msm seção

2023-03-08 20:20 UTC, talDoFlemis commented on src/pages/index.tsx
> +    text: "Fale conosco",
quando se clicka no fale-conosco ele não usa o scroll-smooth

2023-03-09 11:13 UTC, talDoFlemis approved these changes
aprovado

2023-03-09 11:15 UTC, merged