65 improve navbar
ceos-jr/ceos-institucional pull request #78
Opened 2023-03-10 23:29 UTC by Lu1z-Gust4v0

# Description

Link para about page alterado na navbar, remoção do backdrop, correção de bug que travava a navbar ao clicar em um link.

Closes #77
Closes #76
Closes #70 
Closes #69 
Closes #65 

## Tipo de mudança

- [x] Bug fix (mudança não críticaque conserta uma issue)
- [ ] New feature (mudança não crítica que adiciona uma nova feature)
- [ ] Mudança crítica (Concerto ou uma feature que pode quebrar funcionalidades antigas)
- [ ] Apenas mudança de documentação

# Checklist:

- [x] Realizei uma revisão do meu código
- [x] Eu comentei meus códigos, particularmente nas aŕeas mais difíceis
- [ ] Eu fiz as mudanças correspondentes na documentação
- [x] Minhas mudanças não geraram nenhum warning
- [x] Qualquer mudança pendente na main branch já foi implementada nessa branch

2023-03-10 23:59 UTC, talDoFlemis requested changes
nao sei se vale a pena consertar isso daqui, mas se tu conseguir fica mais completa

2023-03-10 23:59 UTC, talDoFlemis commented on src/components/Navbar.tsx
> +  const { lockScroll, unlockScroll, locked, scrollBarCompensation } =
Navbar ela trava a tela quando abre ela está aberta e o usuário redimensona para uma versão que não existe ela

2023-03-11 13:13 UTC, Lu1z-Gust4v0 commented on src/components/Navbar.tsx
> +  const { lockScroll, unlockScroll, locked, scrollBarCompensation } =
Eu acho que não precisa, pq o bug é bem especifico

2023-03-11 16:25 UTC, talDoFlemis approved these changes
aprovado

2023-03-11 17:34 UTC, merged